<#
  DIAGNOSTIC, not a verdict-bearing phase.

  PG.3f's level-2 rig writes '192.0.2.1 <provider>' into the distro's /etc/hosts
  and then re-runs the installer, expecting the provider-route gate to refuse.
  On cfv-180 the rig LANDED (PG.3.CTL fired, getent returned 192.0.2.1) and the
  install nevertheless COMPLETED, with the gate logging a normal PASS nine minutes
  later.

  The install log shows why it is plausible:

    [18:37:53] rig written, getent -> 192.0.2.1
    [18:37:56] Step 4: Restarting WSL.
    [18:37:58] wsl --shutdown exit=0
    [18:46:31] Provider-route gate PASSED: clawuser reached api.anthropic.com:443

  The obvious explanation is that WSL regenerates /etc/hosts on every distro start
  unless [network] generateHosts=false is set. THAT IS AN INFERENCE, and this file
  exists to replace it with a reading, because the fix that follows from it depends
  on which it is. Two candidates and they need different fixes:

    A. WSL regenerated /etc/hosts on restart  -> the rig must set generateHosts=false
    B. something in the install rewrote it    -> a different rig entirely is needed

  A carries a header WSL stamps into the file it generates. B does not.
#>
param(
    [string]$Transcript = 'C:\cfv\hostsdiag-out-probe.txt',
    [string]$LibDir     = 'C:\cfv'
)
$ErrorActionPreference = 'Continue'
. (Join-Path $LibDir 'interim-v120-wslchan.ps1')

function W([string]$m) {
    $line = "[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $m
    Write-Host $line; $line | Out-File $Transcript -Encoding utf8 -Append
}

$r = Invoke-WslFile -Tag 'hostsdiag' -User 'root' -Body @'
echo "=== /etc/wsl.conf, verbatim ==="
cat /etc/wsl.conf 2>&1
echo "=== generateHosts explicitly set? (absent means the WSL default, which is true) ==="
if grep -qi "generateHosts" /etc/wsl.conf 2>/dev/null; then grep -i "generateHosts" /etc/wsl.conf; else echo "GENERATEHOSTS_NOT_SET"; fi
echo "=== /etc/hosts, first 8 lines ==="
head -8 /etc/hosts 2>&1
echo "=== does /etc/hosts carry the header WSL stamps on a file it generated? ==="
if head -3 /etc/hosts | grep -qi "automatically generated by WSL"; then echo "WSL_GENERATED_HEADER=yes"; else echo "WSL_GENERATED_HEADER=no"; fi
echo "=== mtime of /etc/hosts vs boot time (a regenerated file is younger than the boot) ==="
echo "hosts_mtime=$(stat -c %Y /etc/hosts 2>/dev/null)"
echo "boot_epoch=$(($(date +%s) - $(cut -d. -f1 /proc/uptime)))"
echo "now=$(date +%s)"
echo "=== does the provider still resolve normally? (the rig was restored by PG.3e) ==="
getent ahostsv4 api.anthropic.com | awk '{print $1}' | sort -u | tr '\n' ' '; echo
echo "HOSTSDIAG_DONE"
'@
W $r.Out
W 'HOSTSDIAG_PROBE_COMPLETE rc=0'
exit 0
